services:
  app:
    build:
      context: .
    tty: true  # Ensures the terminal is interactive
    stdin_open: true  # Keeps stdin open for interactive input
    environment:
      - OLLAMA_HOST=ollama
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434